[package]
name = "synth"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-stm32 = { version = "0.6.0", features = ["defmt", "stm32u545re", "unstable-pac", "memory-x", "time-driver-tim4", "exti", "chrono"] }

# Embedded HAL utilities
embassy-embedded-hal = { version = "0.5.0", features = ["defmt"] }
embedded-hal-bus = "0.2.0"

# Synchronization primitives and data structures with async support
embassy-sync = { version = "0.7.2", features = ["defmt"] }

# Async/await executor
embassy-executor = { version = "0.9.0", features = ["arch-cortex-m", "executor-thread", "defmt"] }

# Utilities for working with futures, compatible with no_std and not using alloc
embassy-futures = "0.1.2"

# Timekeeping, delays and timeouts
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }

# Math lib
micromath = "2.1.0"

# Memory containers
static_cell = "2.1.1"

# Defmt support
defmt = "1.0.1"
defmt-rtt = "1.1.0"

# Display support
display-interface = "0.5.0"
display-interface-spi = "0.5.0"
mipidsi = "0.8.0"
embedded-graphics = "0.8.1"

# Low level access to Cortex-M processors
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }

# Boostrap crate for Cortex-M Processors
cortex-m-rt = "0.7.5"

# Panic handler that exits `probe-run` with an error code
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
